[build]
  command = "echo 'No build needed'"
  publish = "."

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"